platform :ios, '13.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'RandomMovie' do
  use_frameworks!
  pod 'Sourcery'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'OHHTTPStubs/Swift'
  pod 'MBProgressHUD'
  pod 'Kingfisher'

  target 'RandomMovieSnapshotTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting'
  end

  target 'RandomMovieTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'OHHTTPStubs/Swift'
  end

  target 'RandomMovieUITests' do
    # Pods for testing
  end

end
