platform :ios, '13.0'
inhibit_all_warnings!

target 'RandomMovie' do
  use_frameworks!
  pod 'Sourcery'
  pod 'Moya/RxSwift'

  target 'RandomMovieSnapshotTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'RandomMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RandomMovieUITests' do
    # Pods for testing
  end

end
